name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install build dependencies
      run: sudo apt install -y nasm
    - name: configure
      run: ./configure
    - name: make
      run: make
