name: Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: sudo apt install -y nasm
    - name: Configure
      run: ./config.sh
    - name: Make
      run: make qemu